#global settings
title: Daniel's Blog
description: Personal Blog
author: Daniel Ron
social:
  twitter: edanielron
  linkedin: edwin-daniel-ron-bastidas
  github: edrb2409

plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-octicons


